// src/lib/Footer.svelte
<script lang="ts">

</script>

<footer>
  <span>
    <p>Made by <a href="https://github.com/bananabrann">bananabrann</a></p>
  </span>

  <span>
    <p>All rights reserved.</p>
  </span>  

  <p>
    <a href="https://github.com/bananabrann/barc.bike">Web source code</a>
    |
    <a href="https://github.com/bananabrann/barc.bike/issues">Report an issue</a>
  </p>

</footer>

<style lang="scss">
  footer {
    width: 100%;
    height: 2.5rem;
    background-color: #fff;
    color: #222;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top-left-radius: 1rem;
    border-top-right-radius: 1rem;
  }

  p {
    padding: 0 1rem;
  }

  @media (max-width: 600px) {
    footer {
      font-size: 10px;
    }
  }
</style>

// src/components/footer/footer.tsx
// boilerplate for a new component for Next.js app
//

import React from "react";
import styles from "./footer.module.scss";

const Footer = () => {
  return (
    <footer
      className={`${styles.footer} bg-green-700 w-full text-white p-4 flex flex-row justify-around`}
    >
      <p>
        Made by{" "}
        <a
          target="_blank"
          className="text-yellow-200 transition-all"
          href="https://github.com/bananabrann"
        >
          bananabrann
        </a>
      </p>

      <p>All rights reserved</p>

      <p>
        <a
          target="_blank"
          className="text-yellow-200"
          href="https://github.com/bananabrann/barc.bike/tree/bananabrann/nextjs"
        >
          View source code
        </a>{" "}
        |{" "}
        <a
          target="_blank"
          className="text-yellow-200"
          href="https://github.com/bananabrann/barc.bike/issues"
        >
          Report an issue
        </a>
      </p>
    </footer>
  );
};

export default Footer;
